# Generated by Django 5.0.1 on 2024-03-16 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickuplocation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='location2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dropoflocation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usermanage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('Adress', models.TextField()),
                ('phonenumber', models.CharField(max_length=100)),
                ('licensenumber', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Rental_start_date', models.DateField()),
                ('Rental_end_date', models.DateField()),
                ('Rental_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.car')),
                ('pickuplocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_bookings', to='adminapp.location')),
                ('Dropoflocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_bookings', to='adminapp.location2')),
            ],
        ),
    ]
