# Generated by Django 5.0.1 on 2024-03-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Rent_per_day',
            field=models.IntegerField(default='20000'),
        ),
    ]
